### ISSUE TITLE
Do we want one spec or several?

### ISSUE THREAD

**Issue by mprorock** [mesur-io/post-quantum-signatures#10]
Open question for discussion:
1) Single spec covering PQC signatures and each scheme as a section (this is totally fine for incubation independent of where things shake out)
2) One spec per scheme
3) one spec for broad PQC usage with JOSE and then one spec per scheme that reference that spec

**Comment by OR13** [comment]
For sure to start, we should assume 1 spec... and have it cover key and signature serializations in JSON and CBOR.

I don't think we get a big benefit for splitting CBOR and JSON up, and there is precedent for doing them at the same time... see https://datatracker.ietf.org/doc/html/rfc8812.

I also don't think we get a huge benefit from splitting by crypto system... although I think that could be argued against.

in general, we are defining serializations for lattice and hash based schemes... splitting along those lines would make sense... IF each list was very long and needed a lot of special treatment... but since we are really only looking at serializations I don't think that will be the case... we are not here to define crypto, only serializations of defined crypto.

**Comment by brownoxford** [comment]
I did a quick test and, should we decide to go that route, the build framework will work on any and all `draft*.md` files in the repo.

**Comment by mprorock** [comment]
Resolved by WG
